# Generated by Django 3.2.5 on 2021-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('full_name', models.CharField(max_length=225, null=True)),
                ('roll_no', models.CharField(max_length=225, null=True)),
                ('email', models.EmailField(max_length=225, null=True)),
                ('branch', models.CharField(max_length=225, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
