# Generated by Django 3.2.6 on 2021-08-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REPOSYSAPP', '0009_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
    ]
