# Generated by Django 3.2.6 on 2021-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REPOSYSAPP', '0012_certificate_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='user_id',
            new_name='user',
        ),
    ]
