# Generated by Django 3.2.6 on 2021-08-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REPOSYSAPP', '0015_alter_education_upload_marksheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
