# Generated by Django 3.2.6 on 2021-08-25 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REPOSYSAPP', '0016_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qua_level', models.CharField(max_length=225, null=True)),
                ('country', models.CharField(max_length=225, null=True)),
                ('state', models.CharField(max_length=225, null=True)),
                ('district', models.CharField(max_length=225, null=True)),
                ('college_name', models.CharField(max_length=225, null=True)),
                ('admission_year', models.DateField()),
                ('result', models.CharField(max_length=225, null=True)),
                ('stream', models.CharField(max_length=225, null=True)),
                ('course_name', models.CharField(max_length=225, null=True)),
                ('pass_year', models.DateField()),
                ('percentage', models.CharField(max_length=225, null=True)),
                ('completed', models.CharField(max_length=225, null=True)),
                ('board_university', models.CharField(max_length=225, null=True)),
                ('mode', models.CharField(max_length=225, null=True)),
                ('attempts', models.CharField(max_length=225, null=True)),
                ('upload_marksheet', models.FileField(blank=True, null=True, upload_to='marksheets/%Y/%m/%d/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
