# Generated by Django 3.2.4 on 2021-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REPOSYSAPP', '0018_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table='Certificate',
        ),
        migrations.AlterModelTable(
            name='education',
            table='Education',
        ),
    ]
