# Generated by Django 3.2.4 on 2021-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REPOSYSAPP', '0020_auto_20210928_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_add',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='', max_length=30),
        ),
    ]
